version: "3"
services:
  cache:
    image: redis:alpine

  db:
    image: mongo:3.6
    command: --smallfiles

  app:
    build: .
    restart: always
    env_file:
      - .env
    command: npm start
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - cache
